### ISSUE TITLE
图标有点大

### ISSUE THREAD

**Issue by Adnios** [HanleyLee/Yahei-Consolas-Icon-Hybrid-Font#2]
你好，我在使用该字体，它与saurce code pro nerd font 相比，图标有点大

 第一张图是Yahei-Consolas-Icon-Hybrid-Font，第二张是saurce code pro nerd font 

![image](https://user-images.githubusercontent.com/41060790/90979217-3ec99c80-e586-11ea-9405-3019be4952b6.png)
![image](https://user-images.githubusercontent.com/41060790/90979225-4d17b880-e586-11ea-9ce4-e6c8601e8a1e.png)

**Comment by HanleyLee** [comment]
iconic 字体有很多种, 而且每种字体都有着不同的宽度, 你提到的 saurce code pro nerd font 并不是我这套字体里 Iconic 字体, 所以可能效果会不同, 这是正常的.
